ThrowGrenadeEvent, RelativePosition, Update ItemUseEvent
moelrobi/Synapse pull request #17
Opened 2020-08-13 14:29 UTC by helightdev

2020-08-13 14:40 UTC, helightdev reviewed
RelativePosition: Useful for spawnpoint configurations
PlayerGrenadeThrowEvent: Self explanatory

2020-08-13 15:01 UTC, GrafDimenzio requested changes
Please consider that the rooms have sometimes different rotations
In [Player.RelativePosition](https://github.com/SynapseSL/Synapse/pull/17/commits/d4747b41921b7a6dc5b50ae68c2f7e62593698bf)

2020-08-13 15:08 UTC, helightdev commented
That's why i added this method. It takes the position of the player and substracts the current position of the room, leaving behind the position relative to the room in which the player currently is

2020-08-13 15:10 UTC, helightdev commented
And the setter takes an position which is already relative to the room and translates it to a global position

2020-08-13 15:13 UTC, MineTech13 commented
@GrafDimenzio meint räume haben unterschiedliche Ausrichtungen deine Eigenschaft gibt zwar eine relative Position wieder diese bezieht sich aber nur auf die Raummitte und nicht wo vorne hinten links rechts ist als Beispiel bei dem Micro Raum wo ich recht in von der Micro mir die Position geholt habe bin ich danach beim hin teleportieren in neuen runden Mal links mal rechts gewesen, weil der Raum mal so und mal so gedreht war.

2020-08-13 15:19 UTC, helightdev commented
Oh, sorry war wirklich übersehen, dass die noch Rotation besitzen muss dann kurz noch was überarbeiten

2020-08-13 15:21 UTC, MineTech13 commented
> 
> 
> Oh, sorry war wirklich übersehen, dass die noch Rotation besitzen muss dann kurz noch was überarbeiten

**Hust** Schau mal in das SpawnPointManager Plugin **Hust**

2020-08-13 15:27 UTC, helightdev commented
Gut wusste nicht, dass Transform die Methoden schon hat, war gewohnt so nen Mist immer selbst zu schreiben. Gut dann ist die Funktion sowieso useless - Aber die Anderen Changes fände ich gut ^^

2020-08-14 07:24 UTC, merged

2020-08-14 08:43 UTC, moelrobi commented
Die anderen Changes sind angenommen und RelativePlayerPosition entfernt. Danke für deine PR ^^